version: '3.6'
services:
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
  airflow:
    image: wildflowerschools/wf-deep-docker:airflow-v16
    depends_on:
    - postgres
    restart: always
    command: ["sh", "/scripts/init-and-start.sh"]
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:iamaninsecurepassword@postgres/airflow
      HONEYCOMB_URI: https://honeycomb.api.wildflower-tech.org/graphql
      HONEYCOMB_TOKEN_URI: https://wildflowerschools.auth0.com/oauth/token
      HONEYCOMB_AUDIENCE: https://honeycomb.api.wildflowerschools.org
      HONEYCOMB_CLIENT_ID: EM2pKhXppSchfOW3v0Mp8gn9MVrFn2Mr
      HONEYCOMB_CLIENT_SECRET: 3q4J2PvesXXo0FAhFGe-hHP3sEj_V_LDpIUo0zmcSRLNOhEuy9V2lEsU7UN5njh7
      AWS_ACCESS_KEY_ID: AKIAS7AJ5BXJN5FBH7QR
      AWS_SECRET_ACCESS_KEY: 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
    ports:
      - 9999:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/urandom:/dev/random
    - type: bind
      source: ./scripts
      target: /scripts
    - type: bind
      source: ./dags
      target: /airflow/dags
    - type: bind
      source: ./data
      target: /data
    - type: bind
      source: /data/airflow/logs
      target: /airflow/logs
  airflow-scheduler:
    image: wildflowerschools/wf-deep-docker:airflow-v16
    depends_on:
    - postgres
    - airflow
    restart: always
    command: ["sh", "/scripts/startup-airflow-scheduler.sh"]
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:iamaninsecurepassword@postgres/airflow
      HONEYCOMB_URI: https://honeycomb.api.wildflower-tech.org/graphql
      HONEYCOMB_TOKEN_URI: https://wildflowerschools.auth0.com/oauth/token
      HONEYCOMB_AUDIENCE: https://honeycomb.api.wildflowerschools.org
      HONEYCOMB_CLIENT_ID: EM2pKhXppSchfOW3v0Mp8gn9MVrFn2Mr
      HONEYCOMB_CLIENT_SECRET: 3q4J2PvesXXo0FAhFGe-hHP3sEj_V_LDpIUo0zmcSRLNOhEuy9V2lEsU7UN5njh7
      AWS_ACCESS_KEY_ID: AKIAS7AJ5BXJN5FBH7QR
      AWS_SECRET_ACCESS_KEY: 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
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/urandom:/dev/random
    - type: bind
      source: ./scripts
      target: /scripts
    - type: bind
      source: ./dags
      target: /airflow/dags
    - type: bind
      source: ./data
      target: /data
    - type: bind
      source: /data/airflow/logs
      target: /airflow/logs
    - type: bind
      source: ./airflow.cfg
      target: /airflow/airflow.cfg
  redis:
    image: redis:alpine
    restart: always
    volumes:
    - /data/redis:/data
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
