---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
- kind: ServiceAccount
  name: airflow
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: airflow
