---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  namespace: airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 450Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/airflow/dags"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
